import type { FindingCategory } from "./types"

export const REQUIRED_COLUMNS = [
  "line_id",
  "phone_number",
  "assigned_employee",
  "employee_id",
  "department",
  "cost_center",
  "carrier",
  "plan_name",
  "plan_monthly_cost",
  "data_allowance_gb",
  "data_used_gb",
  "data_used_gb_prev1",
  "data_used_gb_prev2",
  "voice_minutes_used",
  "sms_count",
  "feature_charges",
  "overage_charges",
  "international_roaming_charges",
  "total_monthly_charge",
  "line_status",
  "device_model",
  "activation_date",
  "contract_end_date",
  "billing_period",
] as const

export const SKIP = ""

export type FieldKey = (typeof REQUIRED_COLUMNS)[number]

export type FieldMeta = {
  key: FieldKey
  label: string
  hint: string
  aliases: string[]
  rules: FindingCategory[]
}

export const FIELD_META: FieldMeta[] = [
  {
    key: "line_id",
    label: "Line ID",
    hint: "Carrier row id. We’ll number the rows if you skip this.",
    aliases: ["lineid", "lineno", "linenumber", "recordid", "itemid", "uniqueid"],
    rules: [],
  },
  {
    key: "phone_number",
    label: "Phone number",
    hint: "Wireless number, MDN, or MSISDN.",
    aliases: [
      "phone",
      "phonenumber",
      "phoneno",
      "wirelessnumber",
      "wirelessno",
      "mdn",
      "msisdn",
      "mobile",
      "mobilenumber",
      "mobilephone",
      "cell",
      "cellnumber",
      "subscriber",
      "subscriberno",
    ],
    rules: [],
  },
  {
    key: "assigned_employee",
    label: "Assigned employee",
    hint: "The person on the line. Skip if the export has no owner — we won’t treat every line as unassigned.",
    aliases: [
      "employee",
      "employeename",
      "username",
      "user",
      "assignedto",
      "assigneduser",
      "fullname",
      "name",
      "subscribername",
      "enduser",
      "userfullname",
    ],
    rules: ["unassigned"],
  },
  {
    key: "employee_id",
    label: "Employee ID",
    hint: "Needed to catch a second line on the same person.",
    aliases: ["employeeid", "empid", "userid", "usernumber", "employeenumber", "eid", "personid"],
    rules: ["duplicate"],
  },
  {
    key: "department",
    label: "Department",
    hint: "Shows up on the memo so waste can be routed.",
    aliases: ["dept", "deptname", "departmentname", "businessunit", "bu", "org", "organization"],
    rules: [],
  },
  {
    key: "cost_center",
    label: "Cost center",
    hint: "Finance thinks in cost centers. Skip if you don’t have one.",
    aliases: ["costcenter", "costcentre", "cc", "chargecode", "chargenumber", "glcode", "costcode", "accountcode"],
    rules: [],
  },
  {
    key: "carrier",
    label: "Carrier",
    hint: "Verizon, AT&T, T-Mobile, etc.",
    aliases: ["vendor", "provider", "network", "operator", "serviceprovider"],
    rules: [],
  },
  {
    key: "plan_name",
    label: "Plan name",
    hint: "Rate plan or SOC description.",
    aliases: ["plan", "rateplan", "plandescription", "featureplan", "priceplan", "soc", "serviceplan", "bundle"],
    rules: [],
  },
  {
    key: "plan_monthly_cost",
    label: "Plan monthly cost",
    hint: "Base rate / MRC, before overage.",
    aliases: [
      "mrc",
      "monthlyrecurring",
      "monthlyaccess",
      "accesscharge",
      "plancost",
      "planrate",
      "monthlyrate",
      "baserate",
      "accessfee",
    ],
    rules: ["overage", "oversized"],
  },
  {
    key: "data_allowance_gb",
    label: "Data allowance (GB)",
    hint: "999 or “unlimited” means unlimited. Needed to right-size plans.",
    aliases: ["dataallowance", "allowance", "dataplan", "includeddata", "dataallotment", "datalimit", "gballowance"],
    rules: ["oversized"],
  },
  {
    key: "data_used_gb",
    label: "Data used this period (GB)",
    hint: "Current cycle usage. MB/KB in the header is converted.",
    aliases: ["dataused", "datausage", "usagegb", "datavolume", "currentusage", "data", "kilobytes", "megabytes"],
    rules: ["zero_usage", "duplicate", "oversized"],
  },
  {
    key: "data_used_gb_prev1",
    label: "Data used, prior period",
    hint: "One cycle back. Skip if you only have the current month.",
    aliases: ["datausedprev1", "priorusage", "previoususage", "lastmonthdata", "usageprev1", "data1"],
    rules: ["zero_usage"],
  },
  {
    key: "data_used_gb_prev2",
    label: "Data used, two periods back",
    hint: "Two cycles back. Needed for the 90-day dormant test.",
    aliases: ["datausedprev2", "usageprev2", "data2"],
    rules: ["zero_usage"],
  },
  {
    key: "voice_minutes_used",
    label: "Voice minutes",
    hint: "Needed so a voice-only line isn’t flagged as dormant.",
    aliases: ["voice", "minutes", "voiceminutes", "mou", "airtime", "talkminutes"],
    rules: ["zero_usage"],
  },
  {
    key: "sms_count",
    label: "SMS count",
    hint: "Informational. Not used in the seven tests.",
    aliases: ["sms", "texts", "textcount", "messages", "msgcount"],
    rules: [],
  },
  {
    key: "feature_charges",
    label: "Feature charges",
    hint: "Insurance, add-ons, device payment. Skip if rolled into the total.",
    aliases: ["features", "featurecharge", "addons", "insurance", "devicepayment", "othercharges"],
    rules: [],
  },
  {
    key: "overage_charges",
    label: "Overage charges",
    hint: "Data or plan overage this period.",
    aliases: ["overage", "overagecharge", "dataoverage", "usageoverage", "overageamt"],
    rules: ["overage"],
  },
  {
    key: "international_roaming_charges",
    label: "International roaming",
    hint: "Day-pass and roaming charges.",
    aliases: ["roaming", "intlroaming", "international", "internationalcharges", "daypass", "roamingcharges"],
    rules: ["international"],
  },
  {
    key: "total_monthly_charge",
    label: "Total monthly charge",
    hint: "What was billed this period. If skipped, we add plan + features + overage + roaming.",
    aliases: [
      "total",
      "totalcharge",
      "currentcharges",
      "amount",
      "amountdue",
      "billed",
      "billedamount",
      "monthlytotal",
      "charges",
      "netcharges",
    ],
    rules: [],
  },
  {
    key: "line_status",
    label: "Line status",
    hint: "Active / Suspended. Skip if everything on the bill is active.",
    aliases: ["status", "linestatus", "accountstatus", "state", "linestate"],
    rules: ["suspended"],
  },
  {
    key: "device_model",
    label: "Device model",
    hint: "Informational.",
    aliases: ["device", "model", "handset", "equipment", "make"],
    rules: [],
  },
  {
    key: "activation_date",
    label: "Activation date",
    hint: "Informational.",
    aliases: ["activation", "activated", "startdate", "inception"],
    rules: [],
  },
  {
    key: "contract_end_date",
    label: "Contract end date",
    hint: "Marks dormant lines still in term (ETF). Skip if you don’t have it.",
    aliases: ["contractend", "enddate", "etfdate", "termend", "commitmentend", "contractexpiry"],
    rules: [],
  },
  {
    key: "billing_period",
    label: "Billing period",
    hint: "e.g. 2026-08. Skip if the file is a single period.",
    aliases: ["period", "billperiod", "invoiceperiod", "cycle", "billingcycle", "month"],
    rules: [],
  },
]

export const FIELD_BY_KEY = Object.fromEntries(FIELD_META.map((f) => [f.key, f])) as Record<
  FieldKey,
  FieldMeta
>
